service: dullahan-shead
provider:
  name: aws
  runtime: nodejs8.1.0

functions:
  hello:
    handler: handler.hello
    events:
      - http:
         path: users/create
         method: get

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**
